### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by ZKJGOLD** [xietiansheng/json-to-any-web#1]
path: src/view/home/utils/index.ts
`if (name.includes("_")) {
    name = transformSymbolName(name, "_");
  }
`
hello，can you make this feature optional

**Comment by xietiansheng** [comment]
Ok, Thanks for your feedback

**Comment by xietiansheng** [comment]
![image](https://user-images.githubusercontent.com/34326487/213126171-6c8eca1b-138a-401c-ad8c-c84d08ae1715.png)
![image](https://user-images.githubusercontent.com/34326487/213126359-a0a1fc75-2fcc-43c8-acd7-9cdf04322264.png)
该需求已发布，清空分割字符选项即可！
