### ISSUE TITLE
可选参数的问题

### ISSUE THREAD

**Issue by ecojust** [xietiansheng/json-to-any-web#2]
<img width="1553" alt="image" src="https://github.com/xietiansheng/json-to-any-web/assets/30574854/d03f5ad4-b8ea-4ab4-aa11-1c8fb19af54d">

右边的Data应该是
`export interface Data {
    content?: string;
    memo?: string;
}`
需要加问号吧

**Comment by xietiansheng** [comment]
有道理，感谢反馈

**Comment by xietiansheng** [comment]
![image](https://github.com/xietiansheng/json-to-any-web/assets/34326487/ae64c26d-854e-4ccf-914c-1a5d9f081cee)
新版本已修复，且支持联合类型
