### ISSUE TITLE
给interface添加统一前缀

### ISSUE THREAD

**Issue by ecojust** [xietiansheng/json-to-any-web#3]
能否配置生成的interface名称的格式，现在是data转首字母大写Data；
可否添加额外规则，例如：固定前缀

**Comment by xietiansheng** [comment]
严格意义上来说 interface 与 class 名称都应该是大驼峰规则

**Comment by ecojust** [comment]
因为项目的eslint添加了interface的命名规则，所以想问一下可不可以添加这个配置项（默认前缀为''），跟大驼峰规则不冲突；
<img width="361" alt="image" src="https://github.com/xietiansheng/json-to-any-web/assets/30574854/c5fbe61e-4db1-4f26-8a5b-c8d98ac4a9f9">

**Comment by xietiansheng** [comment]
这个可以的

**Comment by xietiansheng** [comment]
![image](https://github.com/xietiansheng/json-to-any-web/assets/34326487/25c17627-a2b7-4cbf-8983-0e563f78838f)
新版本已发布，支持使用js代码自定义 实体名称
